---

- name: Install nginx
  yum: name=nginx state=installed

- name: Copy the nginx config file
  template:
    src: '{{ conf }}'
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0755
    force: yes
  notify:
    - restart nginx

- name: Enable nginx Systemd Script 
  service:
    name: nginx
    enabled: yes
    state: started