---
- name: Gather EC2 instance metadata
  action: ec2_metadata_facts

- name: Obtain EC2 tags for this instance
  local_action:
    module: ec2_tag
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ ansible_ec2_instance_id }}"
    state: list
  register: ec2_tags
  
- name: Set hostname to match EC2 Name
  hostname: name={{ ec2_tags.tags.Name }}