---

- name: Install python-pycurl
  yum: name=python-pycurl state=installed

- name: Install git
  yum: name=git state=installed  

- name: Install java
  yum: name=java-1.8.0-openjdk state=installed 

- name: Import jenkins Repo key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no

- name: Get jenkins repo info 
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins Package
  yum: name=jenkins state=latest

- name: Enable Systemd Script for Jekins
  service:
    name: jenkins
    enabled: yes
    state: started