---
- hosts: all
  remote_user: centos
  become: yes
  vars:
    serv_name: 'ntpd'
    timeout_val: '120'
  serial: 1

  tasks:

    - name: Check Service Status
      shell: systemctl restart {{ serv_name }}
      register: reg_systemctl

    - debug: var=reg_systemctl.stdout_lines

    - name: Wait for timeout
      wait_for: timeout={{ timeout_val }}
